name = "slack_webhook_client"
version = "1.0.2"

description = "Minimal Gleam client for posting data to a Slack incoming Webhook"
licences = ["Apache-2.0"]
repository = { type = "github", user = "iindyverse", repo = "slack_webhook_client" }
links = []

[dependencies]
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
oas_generator_utils = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
argv = ">= 1.0.2 and < 2.0.0"
gleeunit = ">= 1.0.0 and < 1.9.0"
oas_generator = ">= 2.3.1 and < 3.0.0"
simplifile = ">= 2.3.2 and < 3.0.0"
snag = ">= 1.2.0 and < 2.0.0"
